import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Clock3, Mail, MapPin, MessageCircle, Phone, Send } from "lucide-react";
import { useState, type FormEvent } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PageIntro, WHATSAPP_URL } from "@/components/site-layout";

const quoteSchema = z.object({
  name: z.string().trim().min(3, "Ingrese su nombre completo.").max(100),
  company: z.string().trim().min(2, "Ingrese su institución o empresa.").max(150),
  email: z.string().trim().email("Ingrese un correo válido.").max(255),
  phone: z.string().trim().min(7, "Ingrese un teléfono válido.").max(30).regex(/^[+\d\s()-]+$/, "Ingrese un teléfono válido."),
  area: z.string().min(1, "Seleccione un área de interés."),
  details: z.string().trim().min(15, "Describa su requerimiento con al menos 15 caracteres.").max(1500),
});
type Errors = Partial<Record<keyof z.infer<typeof quoteSchema>, string>>;

export const Route = createFileRoute("/contacto")({ head:()=>({meta:[
 {title:"Contacto y cotizaciones | Eduland Technology"},{name:"description",content:"Solicite una cotización de equipamiento educativo, científico o industrial para su institución en Perú."},{property:"og:title",content:"Contacto y cotizaciones | Eduland Technology"},{property:"og:description",content:"Cuéntenos su requerimiento y reciba orientación para su proyecto institucional."},{property:"og:type",content:"website"},{property:"og:url",content:"/contacto"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/contacto"}]}), component: ContactPage });

const areas=["Módulos educativos técnicos","Laboratorios de ciencias básicas","Instrumentación y medición","Software y licenciamiento técnico","Servicios y postventa","Otro requerimiento"];
function ContactPage(){const [area,setArea]=useState("");const [errors,setErrors]=useState<Errors>({});const [sent,setSent]=useState(false);
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const parsed=quoteSchema.safeParse({name:form.get("name"),company:form.get("company"),email:form.get("email"),phone:form.get("phone"),area,details:form.get("details")});if(!parsed.success){const next:Errors={};for(const issue of parsed.error.issues){const key=issue.path[0] as keyof Errors;if(!next[key])next[key]=issue.message;}setErrors(next);setSent(false);return;}setErrors({});setSent(true);const d=parsed.data;const message=`Hola Eduland Technology, deseo solicitar una cotización.\n\nNombre: ${d.name}\nInstitución: ${d.company}\nCorreo: ${d.email}\nTeléfono: ${d.phone}\nÁrea: ${d.area}\nRequerimiento: ${d.details}`;window.open(`https://wa.me/51933309204?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer");}
 return <><PageIntro eyebrow="Contacto y cotizaciones" title="Conversemos sobre su requerimiento técnico" description="Comparta el alcance inicial de su proyecto. Organizaremos la información para orientar la selección y cotización del equipamiento adecuado."/><section className="py-20"><div className="page-shell grid gap-8 lg:grid-cols-[1.35fr_0.65fr]"><form onSubmit={submit} noValidate className="rounded-md border border-border bg-card p-6 sm:p-10"><div><p className="eyebrow">Formulario B2B</p><h2 className="mt-3 text-2xl font-bold text-ink">Solicite una cotización</h2><p className="mt-2 text-sm text-muted-foreground">Los campos marcados son necesarios para preparar su consulta.</p></div>{sent&&<div role="status" className="mt-6 flex gap-3 rounded-md border border-primary/25 bg-secondary p-4 text-sm text-secondary-foreground"><CheckCircle2 className="size-5 shrink-0 text-primary"/><span><strong>Requerimiento preparado.</strong> Se abrió WhatsApp para que pueda enviarlo directamente.</span></div>}<div className="mt-8 grid gap-6 sm:grid-cols-2"><Field label="Nombre completo" error={errors.name}><Input name="name" autoComplete="name" maxLength={100} aria-invalid={Boolean(errors.name)} /></Field><Field label="Institución / Empresa" error={errors.company}><Input name="company" autoComplete="organization" maxLength={150} aria-invalid={Boolean(errors.company)} /></Field><Field label="Correo corporativo" error={errors.email}><Input name="email" type="email" autoComplete="email" maxLength={255} placeholder="nombre@institucion.com" aria-invalid={Boolean(errors.email)} /></Field><Field label="Teléfono / Celular" error={errors.phone}><Input name="phone" type="tel" autoComplete="tel" maxLength={30} placeholder="+51 999 999 999" aria-invalid={Boolean(errors.phone)} /></Field><div className="sm:col-span-2"><Field label="Área o equipo de interés" error={errors.area}><Select value={area} onValueChange={setArea}><SelectTrigger className="h-11" aria-invalid={Boolean(errors.area)}><SelectValue placeholder="Seleccione una categoría"/></SelectTrigger><SelectContent>{areas.map(item=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></Field></div><div className="sm:col-span-2"><Field label="Detalle del requerimiento" error={errors.details}><Textarea name="details" rows={6} maxLength={1500} placeholder="Indique equipos, cantidades, aplicación, plazo referencial u otras especificaciones." aria-invalid={Boolean(errors.details)} /></Field></div></div><Button type="submit" size="lg" className="mt-7 w-full sm:w-auto"><Send/>Preparar solicitud por WhatsApp</Button></form>
 <aside className="rounded-md bg-ink p-7 text-primary-foreground sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.16em] text-sky">Datos directos</p><h2 className="mt-4 text-2xl font-bold">Atención comercial</h2><div className="mt-8 grid gap-6">{[{icon:MapPin,label:"Dirección fiscal / operativa",value:"San Isidro, Lima - Perú"},{icon:Mail,label:"Correo institucional",value:"ventas@edulandtech.com"},{icon:Phone,label:"Teléfono / WhatsApp",value:"+51 933 309 204"},{icon:Clock3,label:"Horario de atención",value:"Atención comercial con previa coordinación"}].map(({icon:Icon,label,value})=><div key={label} className="flex gap-4 border-b border-primary-foreground/12 pb-6 last:border-0"><Icon className="mt-1 size-5 shrink-0 text-sky"/><div><p className="text-xs font-semibold uppercase text-primary-foreground/50">{label}</p><p className="mt-1 text-sm leading-6">{value}</p></div></div>)}</div><Button asChild variant="sky" size="lg" className="mt-8 w-full"><a href={WHATSAPP_URL} target="_blank" rel="noreferrer"><MessageCircle/>Iniciar chat ahora</a></Button></aside></div></section></>}
function Field({label,error,children}:{label:string;error:string|undefined;children:React.ReactNode}){return <label className="grid gap-2 text-sm font-semibold text-foreground"><span>{label} *</span>{children}{error&&<span className="text-xs font-medium text-destructive">{error}</span>}</label>}
