import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Globe2, Headset, Route as RouteIcon, Target } from "lucide-react";
import { PageIntro, QuoteBand } from "@/components/site-layout";
import { SectionHeading } from "@/components/section-heading";
import serviceImage from "@/assets/technical-service.jpg";

export const Route = createFileRoute("/nosotros")({ head: () => ({ meta: [
  { title: "Nosotros | Eduland Technology S.R.L." }, { name: "description", content: "Conozca a Eduland Technology, socio estratégico para equipamiento educativo, científico e industrial en Perú." },
  { property: "og:title", content: "Nosotros | Eduland Technology" }, { property: "og:description", content: "Tecnología educativa y científica con asesoramiento técnico y soporte local." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/nosotros" }, { name: "twitter:card", content: "summary_large_image" },
], links: [{ rel: "canonical", href: "/nosotros" }] }), component: AboutPage });

function AboutPage(){return <><PageIntro eyebrow="Nuestra empresa" title="Tecnología con propósito educativo y productivo" description="Somos un socio estratégico para instituciones que buscan implementar espacios de aprendizaje práctico, investigación y desarrollo tecnológico con una visión integral."/>
<section className="py-24"><div className="page-shell grid items-center gap-14 lg:grid-cols-2"><div><SectionHeading eyebrow="Quiénes somos" title="Conectamos necesidades formativas con soluciones especializadas"/><p className="section-description">Eduland Technology S.R.L. se enfoca en la importación, distribución e integración de tecnología educativa y científica para universidades, institutos, centros de investigación y empresas.</p><p className="section-description">Analizamos cada requerimiento desde su aplicación académica o técnica para orientar la selección, configuración y puesta en servicio del equipamiento.</p></div><img src={serviceImage} alt="Especialistas realizando la puesta en marcha de un laboratorio" className="aspect-[4/3] w-full rounded-md object-cover" loading="lazy" width="1408" height="912"/></div></section>
<section className="bg-ink py-24 text-primary-foreground"><div className="page-shell grid gap-px overflow-hidden rounded-md bg-primary-foreground/15 md:grid-cols-2"><article className="bg-ink p-8 md:p-12"><Target className="size-8 text-sky"/><p className="mt-8 text-xs font-bold uppercase tracking-[0.16em] text-sky">Misión</p><p className="mt-4 text-lg leading-8 text-primary-foreground/85">Importar y comercializar módulos educativos innovadores y equipamiento de alta calidad para laboratorios, destinados a instituciones educativas y empresas, con el fin de apoyar la educación práctica y el desarrollo científico.</p></article><article className="bg-ink p-8 md:p-12"><RouteIcon className="size-8 text-sky"/><p className="mt-8 text-xs font-bold uppercase tracking-[0.16em] text-sky">Visión</p><p className="mt-4 text-lg leading-8 text-primary-foreground/85">Ser la empresa líder en el suministro de soluciones educativas y científicas en Perú, destacándose por la calidad de nuestros productos, un excelente servicio al cliente y el impulso a la educación tecnológica y científica.</p></article></div></section>
<section className="py-24"><div className="page-shell"><SectionHeading eyebrow="Objetivos estratégicos" title="Construimos capacidad institucional sostenible"/><div className="mt-12 grid gap-6 md:grid-cols-3">{[[Globe2,"Alianzas internacionales","Articular una oferta especializada con fabricantes líderes y tecnologías relevantes para el aprendizaje aplicado."],[RouteIcon,"Cobertura nacional","Atender proyectos educativos, científicos e industriales en las distintas regiones del Perú."],[Headset,"Soporte de primer nivel","Asegurar acompañamiento técnico cercano durante la implementación y operación de cada solución."]].map(([Icon,title,text],i)=><article key={title as string} className="border-t-2 border-primary bg-card pt-7"><span className="font-mono text-xs text-muted-foreground">0{i+1}</span><Icon className="mt-6 size-7 text-primary"/><h3 className="mt-5 text-lg font-bold text-ink">{title as string}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text as string}</p></article>)}</div><div className="mt-16 flex flex-col gap-8 rounded-md bg-secondary p-8 md:flex-row md:items-center md:p-12"><CheckCircle2 className="size-12 shrink-0 text-primary"/><div><h2 className="text-2xl font-bold text-ink">Compromiso de calidad</h2><p className="mt-3 max-w-4xl leading-7 text-muted-foreground">Brindamos asesoramiento técnico personalizado de acuerdo con los objetivos, especificaciones y condiciones de cada cliente, priorizando una selección clara y una implementación responsable.</p></div></div></div></section><QuoteBand title="Conversemos sobre su próximo proyecto" text="Podemos ayudarle a estructurar el alcance técnico y la solución más adecuada para su institución."/></>}
