import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Boxes, Check, GraduationCap, Settings, Ship } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro, QuoteBand } from "@/components/site-layout";
import serviceImage from "@/assets/technical-service.jpg";

export const Route = createFileRoute("/servicios")({head:()=>({meta:[
 {title:"Servicios y postventa | Eduland Technology"},{name:"description",content:"Importación, instalación, capacitación, mantenimiento y repuestos para equipamiento educativo y científico."},{property:"og:title",content:"Servicios técnicos y postventa | Eduland Technology"},{property:"og:description",content:"Acompañamiento técnico integral para laboratorios y equipos especializados."},{property:"og:type",content:"website"},{property:"og:url",content:"/servicios"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/servicios"}]}),component:ServicesPage});
const services=[
 {icon:Ship,n:"01",title:"Importación directa y gestión logística",text:"Coordinamos el suministro de equipamiento desde fabricantes globales, considerando documentación, transporte y entrega para cada proyecto.",points:["Evaluación de alternativas técnicas","Coordinación documental y logística","Seguimiento hasta la entrega"]},
 {icon:Boxes,n:"02",title:"Instalación y puesta en marcha",text:"Realizamos el montaje, integración y las pruebas operativas requeridas en los espacios del cliente antes de iniciar su uso.",points:["Verificación de condiciones del laboratorio","Montaje e integración de componentes","Pruebas funcionales de aceptación"]},
 {icon:GraduationCap,n:"03",title:"Capacitación y transferencia tecnológica",text:"Preparamos sesiones prácticas para docentes, laboratoristas y personal técnico, enfocadas en el uso seguro y productivo de las soluciones.",points:["Entrenamiento orientado a usuarios","Prácticas de operación y seguridad","Material de apoyo técnico"]},
 {icon:Settings,n:"04",title:"Calibración, mantenimiento y repuestos",text:"Estructuramos planes preventivos y correctivos, junto con la gestión de repuestos originales, para proteger la continuidad operativa.",points:["Diagnóstico y mantenimiento programado","Gestión de repuestos compatibles","Asistencia técnica postventa"]},
];
function ServicesPage(){return <><PageIntro eyebrow="Servicios y postventa" title="Acompañamiento técnico durante todo el ciclo del proyecto" description="Integramos suministro, implementación y soporte para que cada laboratorio opere con claridad, seguridad y continuidad."/><section className="py-24"><div className="page-shell grid items-center gap-14 lg:grid-cols-[1.1fr_0.9fr]"><img src={serviceImage} alt="Especialistas de servicio técnico en laboratorio de automatización" className="aspect-[4/3] w-full rounded-md object-cover" loading="lazy" width="1408" height="912"/><div><p className="eyebrow">Capacidad operativa</p><h2 className="section-title">De la especificación a la operación</h2><p className="section-description">Nuestro enfoque permite coordinar las etapas críticas de una adquisición especializada, reduciendo fricciones entre la selección del equipo, su instalación y el uso por parte del equipo académico o técnico.</p><Button asChild className="mt-7"><Link to="/contacto">Coordinar una asesoría <ArrowRight/></Link></Button></div></div></section><section className="border-t border-border bg-panel py-24"><div className="page-shell grid gap-px overflow-hidden rounded-md border border-border bg-border md:grid-cols-2">{services.map(({icon:Icon,...service})=><article key={service.n} className="bg-background p-8 md:p-10"><div className="flex items-center justify-between"><Icon className="size-8 text-primary"/><span className="font-mono text-xs text-muted-foreground">SERVICIO {service.n}</span></div><h2 className="mt-10 text-2xl font-bold text-ink">{service.title}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{service.text}</p><ul className="mt-7 grid gap-3">{service.points.map(point=><li key={point} className="flex gap-3 text-sm font-medium text-foreground"><Check className="mt-0.5 size-4 shrink-0 text-primary"/>{point}</li>)}</ul></article>)}</div></section><QuoteBand title="Proteja la continuidad de su laboratorio" text="Solicite una propuesta de implementación, capacitación o soporte adaptada al equipamiento de su institución."/></>}
